config/routes.rb
Isma::Application.routes.draw do
  
  get 'admin' => 'admin#index'
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  resources :feedbacks

  resources :comments

  resources :users

  resources :requests
  
  resources :posts

  root :to => 'requests#new', as: 'index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :users
end

app/models/department.rb
class Department < ActiveRecord::Base
  belongs_to :users
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :users
end

app/models/priority.rb
class Priority < ActiveRecord::Base
  has_many :requests
end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :users
  belongs_to :requests
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
end

app/models/status.rb
class Status < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
has_many :requests
has_many :departments
has_many :posts
has_many :comments
belongs_to :roles
email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

validates :login, :presence => true,
		  :length => { :maximum => 50 },
		  :uniqueness => true
validates :email, :presence => true,
		  :format => { :with => email_regex },
		  :uniqueness => { :case_sensitive => false }
has_secure_password
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end

end

app/controllers/index_controller.rb
class StartController < ApplicationController
  def index
    @posts=Post.all
    @users=User.all
    
    respond_to do |format|
      format.html # index.html.erb
    end    
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_url, notice: '' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to posts_url, notice: '' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: ''  }
      format.json { head :ok }
    end
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @requests }
    end
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
    @request = Request.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @request }
    end
  end

  # GET /requests/new
  # GET /requests/new.json
  def new
    @request = Request.new
    @posts = Post.order("updated_at DESC").limit(5)
    @guest_id = Role.find_by_name("guest").id
    if session[:user_id]
      @user_email = User.find(session[:user_id]).email
    end
    if session[:user_id]
      @user_phone = User.find(session[:user_id]).phone
    end
    if session[:user_id]
      @informer = User.find(session[:user_id]).first_name + " " + User.find(session[:user_id]).last_name
    end
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @request }
    end
  end

  # GET /requests/1/edit
  def edit
    @request = Request.find(params[:id])
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(params[:request])

    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render json: @request, status: :created, location: @request }
      else
        format.html { render action: "new" }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /requests/1
  # PUT /requests/1.json
  def update
    @request = Request.find(params[:id])

    respond_to do |format|
      if @request.update_attributes(params[:request])
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request = Request.find(params[:id])
    @request.destroy

    respond_to do |format|
      format.html { redirect_to requests_url }
      format.json { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  :attr_accessible
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: '' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to users_url, notice: '' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: ''  }
      format.json { head :ok }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/requests/_form.html.erb
<%= form_for(@request) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="hidden">
    <%= f.label :user_id %><br />
    <% if session[:user_id] %>
      <%= f.text_field :user_id, :value => session[:user_id] %>
    <% else %>
      <%= f.text_field :user_id, :value => @guest_id %>
    <% end %>
  </div>
  <div class=informer>
    <%= f.label 'Кто Вы?' %><br />
    <% if session[:user_id] %>
      <%= f.text_field :informer, :value => @informer %>
    <% else %>
      <%= f.text_field :informer, :placeholder => "Ваше имя" %>
    <% end %>
  </div>
  <div class=field>
    <%= f.label :department_id, 'Откуда Вы?' %><br />
    <%= f.select :department_id, options_for_select= Department.all.collect {|p| [p.name, p.id] }, {:include_blank => ''} %>
  </div>
  <div class="field">
    <%= f.label :description, 'Чего Вы хотите?' %><br />
    <%= f.text_area :description, :cols => 60, :rows => 10 %>
  </div>
  <div class="field">
    <%= f.label :comment, 'Что нам еще важно знать?' %><br />
    <%= f.text_area :comment, :cols => 60, :rows => 5 %>
  </div>
  <div class=contactmail>
    <%= f.label 'Как с Вами связаться' %><br />
    <% if session[:user_id] %>
      <%= f.email_field :mail, :value => @user_email%>
    <% else %>
      <%= f.email_field :mail, :placeholder => "Электронная почта" %>
    <% end %>
  </div>
  <div class=contactphone>
    <% if session[:user_id] %>
      <%= f.telephone_field :phone, :value => @user_phone %>
    <% else %>
      <%= f.telephone_field :phone, :placeholder => "Номер телефона" %>
    <% end %>   
  </div>
  <div class="hidden">
    <%= f.label :status_id %><br />
    <%= f.select :status_id, options_for_select= Status.all.collect {|p| [p.status_name, p.id] }, {:include_blank => ''} %>
  </div>
  <div class="hidden">
    <%= f.label :priority_id %><br />
    <%= f.select :priority_id, options_for_select= Priority.all.collect {|p| [p.name, p.id] }, {:include_blank => ''} %>
  </div>
  <div class="hidden">
    <%= f.label :master_id, 'Прозвище мастера' %><br />
    <%= f.select :master_id, options_for_select= User.order("last_name").select("first_name, last_name").find_all_by_role_id([1,2]).collect {|p| [p.first_name + " " + p.last_name, p.id] }, {:include_blank => ''} %>
  </div>
  <div class="actions">
    <%= f.submit 'Послать мольбу о помощи', :class => "button" %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing request</h1>

<%= render 'form' %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<h2><span class="headline2">Перечень заявок<span></h2>

<table>
  <tr>
    <th>User</th>
    <th>Department</th>
    <th>Description</th>
    <th>Comment</th>
    <th>Status</th>
    <th>Priority</th>
    <th>Master</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @requests.each do |request| %>
  <tr>
    <td><%= request.user_id %></td>
    <td><%= request.department_id %></td>
    <td><%= request.description %></td>
    <td><%= request.comment %></td>
    <td><%= request.status_id %></td>
    <td><%= request.priority_id %></td>
    <td><%= request.master_id %></td>
    <td><%= link_to 'Show', request %></td>
    <td><%= link_to 'Edit', edit_request_path(request) %></td>
    <td><%= link_to 'Destroy', request, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Request', new_request_path %>

app/views/requests/new.html.erb
<div id=request>
<div class=invite><p>
<%= link_to "Регистрация", new_user_path %>
на сайте - путь к новым возможностям</div>
<div class=form>
<%= render 'form' %>
</div>
</div>
<%= render("news/new") %>
<div class=clear></div>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @request.user_id %>
</p>

<p>
  <b>Department:</b>
  <%= @request.department_id %>
</p>

<p>
  <b>Description:</b>
  <%= @request.description %>
</p>

<p>
  <b>Comment:</b>
  <%= @request.comment %>
</p>

<p>
  <b>Status:</b>
  <%= @request.status_id %>
</p>

<p>
  <b>Priority:</b>
  <%= @request.priority_id %>
</p>

<p>
  <b>Master:</b>
  <%= @request.master_id %>
</p>


<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>