config/routes.rb
Isma::Application.routes.draw do
  
  get 'admin' => 'admin#index'
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  resources :feedbacks

  resources :comments

  resources :users

  resources :requests
  
  resources :posts

  root :to => 'requests#new', as: 'index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :users
end

app/models/department.rb
class Department < ActiveRecord::Base
  belongs_to :users
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :users
end

app/models/priority.rb
class Priority < ActiveRecord::Base
  has_many :requests
end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :users
  belongs_to :requests
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
end

app/models/status.rb
class Status < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
has_many :requests
has_many :departments
has_many :posts
has_many :comments
belongs_to :roles
email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

validates :login, :presence => true,
		  :length => { :maximum => 50 },
		  :uniqueness => true
validates :email, :presence => true,
		  :format => { :with => email_regex },
		  :uniqueness => { :case_sensitive => false }
has_secure_password
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end

end

app/controllers/index_controller.rb
class StartController < ApplicationController
  def index
    @posts=Post.all
    @users=User.all
    
    respond_to do |format|
      format.html # index.html.erb
    end    
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html>
<head>
<%= stylesheet_link_tag 'application', :media => 'screen' %>
<meta charset="UTF-8" />
<title>ISMA - Support</title>
<%= csrf_meta_tag %>
</head>
<body class=<%= controller.controller_name %>>
<header>
<%= image_tag("isma64.png", :size => "48x48", :alt => "Logo", :class => "img-left", :title => "ИвГМА") %>
<h1>Техподдержка ИвГМА - мы лечим компьютеры</h1>
</header>
<section id="content">
<%= yield %>
</section>
<footer>
<address>Наш адрес: г. Иваново, пр-т Ф. Энгельса, 8, 2 эт. Тел. (4932) 30-06-70</address>
</footer>
<nav>
<%= link_to(index_path) do %>
<div class=nav><p <%= if controller.controller_name=="requests" then "class=current" end %>><%= image_tag("bookmark-new.png", :size=>"22x22", :alt=>"Подать заявку", :title => "Подать заявку") %><span class=invis>&nbspПодать заявку</span></div>
<% end %>
<%= link_to() do %>
<div class=nav><p><%= image_tag("meeting-observer.png", :size=>"22x22", :alt=>"Статус заявки", :title => "Статус заявки") %><span class=invis>&nbspСтатус заявки</span></div>
<% end %>
<%= link_to(posts_path) do %>
<div class=nav><p <%= if current_page?(:controller => "posts") then "class=current" end %>><%= image_tag("news-subscribe.png", :size=>"22x22", :alt=>"Новости", :title => "Новости") %><span class=invis>&nbspНовости</span></div>
<% end %>
<%= link_to(new_feedback_path) do %>
<div class=nav><p <%= if current_page?(:controller => "feedbacks", :action => "new") then "class=current" end %>><%= image_tag("mail-mark-unread-new.png", :size=>"22x22", :alt=>"Связаться с нами", :title => "Связаться с нами") %><span class=invis>&nbspСвязаться с нами</span></div>
<% end %>
<% if session[:user_id] %>
  <%= link_to(logout_path) do %>
    <div class=signin><p <%= if controller.controller_name=="sessions" then "class=current" end %>><%= image_tag("dialog-password.png", :size=>"22x22", :alt=>"Войти") %><span class=invis>&nbspВыйти</span></div>
  <% end %>
<% else %>
  <%= link_to(login_path) do %>
    <div class=signin><p <%= if controller.controller_name=="sessions" then "class=current" end %>><%= image_tag("dialog-password.png", :size=>"22x22", :alt=>"Войти") %><span class=invis>&nbspВойти</span></div>
  <% end %>
<% end %>
<% if session[:user_id] %>
  <div class=signin><p class=wellcom>Добро пожаловать,&nbsp <%= User.find_by_id(session[:user_id]).first_name  %> </div>
<% end %>
</nav>
</body>
</html>